name: rotation_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Used for UI block
  pinput: ^0.2.6
  flutter_svg: ^0.20.0-nullsafety.3
  group_button: ^1.1.0
  md2_tab_indicator: ^1.0.2
  form_field_validator: ^1.0.1
  mask_text_input_formatter: ^1.2.1
  flutter_calendar_carousel: ^1.5.2

  # Used for logic block
  dio: 3.0.10
  http: ^0.12.2
  rxdart: ^0.24.1
  provider: ^4.3.3
  equatable: ^1.2.5
  flutter_html: ^0.8.2
  url_launcher: ^5.7.10
  path_provider: ^1.6.27
  firebase_core: ^0.5.0+1
  flutter_downloader: ^1.5.2
  firebase_messaging: ^7.0.3
  permission_handler: ^5.1.0+2
  shared_preferences: ^0.5.12+4


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svg/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Root
      fonts:
        - asset: assets/fonts/PT_Root_UI_Bold.ttf
          weight: 900
        - asset: assets/fonts/PT_Root_UI_Bold.ttf
          weight: 800
        - asset: assets/fonts/PT_Root_UI_Bold.ttf
          weight: 700
        - asset: assets/fonts/PT_Root_UI_Medium.ttf
          weight: 600
        - asset: assets/fonts/PT_Root_UI_Medium.ttf
          weight: 500
        - asset: assets/fonts/PT_Root_UI_Regular.ttf
          weight: 400
        - asset: assets/fonts/PT_Root_UI_Light.ttf
          weight: 300
        - asset: assets/fonts/PT_Root_UI_Light.ttf
          weight: 200
